=== ISO-TC211/iso-geodetic-registry/src/iso-registry-api/src/main/resources/schema/excelAdapterConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:bxl="http://www.bespire.de/io/excel" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="http://www.bespire.de/io/excel">
	<xs:complexType name="ExcelConfiguration">
		<xs:sequence>
			<xs:element name="sheet" type="bxl:SheetConfiguration" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ExcelConfiguration" type="bxl:ExcelConfiguration"/>
	<!-- .................... -->
	<xs:complexType name="SheetConfiguration">
		<xs:sequence>
			<xs:element name="importType" type="xs:string"/>
			<xs:element name="exportType" type="xs:string"/>
			<xs:element name="itemClassName" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="column" type="bxl:ColumnConfiguration" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="sheetName" type="xs:string" use="required"/>
		<xs:attribute name="idColumn" type="xs:string" use="required"/>
		<xs:attribute name="idPrefix" type="xs:string" use="required"/>
		<xs:attribute name="headerRow" type="xs:int" use="optional" default="1"/>
		<xs:attribute name="firstDataRow" type="xs:int" use="optional" default="2"/>
		<xs:attribute name="firstDataColumn" type="xs:string" use="optional" default="B"/>
	</xs:complexType>
	<xs:element name="SheetConfiguration" type="bxl:SheetConfiguration"/>
	<!-- .................... -->
	<xs:complexType name="ColumnConfiguration">
		<xs:sequence>
			<xs:element name="javaProperty" type="xs:string"/>
			<xs:element name="javaPropertyExport" type="xs:string" minOccurs="0"/>
			<xs:element name="multiple" type="xs:boolean" default="false"/>
			<xs:element name="references" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="columnName" type="xs:string" use="required"/>
		<xs:attribute name="separatorChar" type="xs:string" use="optional" default=";"/>
	</xs:complexType>
	<xs:element name="ColumnConfiguration" type="bxl:ColumnConfiguration"/>
</xs:schema>

=== ISO-TC211/iso-geodetic-registry/src/iso-registry-client/src/main/resources/isoExcelConfiguration.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ExcelConfiguration xmlns="http://www.bespire.de/io/excel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bespire.de/io/excel file:///D:/src/git/iso-registry/src/iso-registry-api/src/main/resources/schema/excelAdapterConfiguration.xsd">
	<sheet sheetName="Source_Citation(CI#)" idColumn="A" idPrefix="CI" headerRow="2" firstDataRow="4" firstDataColumn="B">
		<importType>org.iso.registry.api.registry.registers.gcp.CitationDTO</importType>
		<exportType>de.geoinfoffm.registry.core.model.iso19115.CI_Citation</exportType>
		<column columnName="B">
			<javaProperty>title</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="C">
			<javaProperty>alternateTitle</javaProperty>
			<multiple>true</multiple>
		</column>
		<column columnName="D">
			<javaProperty>author</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="E">
			<javaProperty>publisher</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="F">
			<javaProperty>publicationDate</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="G">
			<javaProperty>revisionDate</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="H">
			<javaProperty>edition</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="I">
			<javaProperty>editionDate</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="J">
			<javaProperty>series.name</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="K">
			<javaProperty>series.issueIdentification</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="L">
			<javaProperty>series.page</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="M">
			<javaProperty>otherCitationDetails</javaProperty>
			<multiple>false</multiple>
		</column>
	</sheet>
	<sheet sheetName="UoM(UM#)" idColumn="A" idPrefix="UM" headerRow="2" firstDataRow="4" firstDataColumn="B">
		<importType>org.iso.registry.api.registry.registers.gcp.UnitOfMeasureItemProposalDTO</importType>
		<exportType>org.iso.registry.core.model.UnitOfMeasureItem</exportType>
		<itemClassName>UnitOfMeasure</itemClassName>
		<column columnName="B">
			<javaProperty>name</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="C">
			<javaProperty>aliases</javaProperty>
			<multiple>true</multiple>
		</column>
		<column columnName="D">
			<javaProperty>remarks</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="E">
			<javaProperty>standardUnit</javaProperty>
			<multiple>false</multiple>
			<references>UoM(UM#)</references>
		</column>
		<column columnName="F">
			<javaProperty>scaleToStandardUnitNumerator</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="G">
			<javaProperty>scaleToStandardUnitDenominator</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="H">
			<javaProperty>measureType</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="I">
			<javaProperty>symbol</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="J">
			<javaProperty>informationSource</javaProperty>
			<multiple>true</multiple>
			<references>Source_Citation(CI#)</references>
		</column>
		<column columnName="K">
			<javaProperty>justification</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="L">
			<javaProperty>registerManagerNotes</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="M">
			<javaProperty>controlBodyNotes</javaProperty>
			<multiple>false</multiple>
		</column>
	</sheet>
	<sheet sheetName="Pr_Meridian(PM#)" idColumn="A" idPrefix="PM" headerRow="2" firstDataRow="4" firstDataColumn="B">
		<importType>org.iso.registry.api.registry.registers.gcp.PrimeMeridianItemProposalDTO</importType>
		<exportType>org.iso.registry.core.model.datum.PrimeMeridianItem</exportType>
		<itemClassName>PrimeMeridian</itemClassName>
		<column columnName="B">
			<javaProperty>name</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="C">
			<javaProperty>aliases</javaProperty>
			<multiple>true</multiple>
		</column>
		<column columnName="D">
			<javaProperty>remarks</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="E">
			<javaProperty>greenwichLongitude</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="F">
			<javaProperty>greenwichLongitudeUom</javaProperty>
			<multiple>false</multiple>
			<references>UoM(UM#)</references>
		</column>
		<column columnName="G">
			<javaProperty>informationSource</javaProperty>
			<multiple>true</multiple>
			<references>Source_Citation(CI#)</references>
		</column>
		<column columnName="H">
			<javaProperty>justification</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="I">
			<javaProperty>registerManagerNotes</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="J">
			<javaProperty>controlBodyNotes</javaProperty>
			<multiple>false</multiple>
		</column>
	</sheet>
	<sheet sheetName="Ellips(EL#)" idColumn="A" idPrefix="EL" headerRow="2" firstDataRow="4" firstDataColumn="B">
		<importType>org.iso.registry.api.registry.registers.gcp.EllipsoidItemProposalDTO</importType>
		<exportType>org.iso.registry.core.model.datum.EllipsoidItem</exportType>
		<itemClassName>Ellipsoid</itemClassName>
		<column columnName="B">
			<javaProperty>name</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="C">
			<javaProperty>aliases</javaProperty>
			<multiple>true</multiple>
		</column>
		<column columnName="D">
			<javaProperty>remarks</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="E">
			<javaProperty>semiMajorAxis</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="F">
			<javaProperty>semiMajorAxisUom</javaProperty>
			<multiple>false</multiple>
			<references>UoM(UM#)</references>
		</column>
		<column columnName="G">
			<javaProperty>sphere</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="H">
			<javaProperty>inverseFlattening</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="I">
			<javaProperty>semiMinorAxis</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="J">
			<javaProperty>informationSource</javaProperty>
			<multiple>true</multiple>
			<references>Source_Citation(CI#)</references>
		</column>
		<column columnName="K">
			<javaProperty>justification</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="L">
			<javaProperty>registerManagerNotes</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="M">
			<javaProperty>controlBodyNotes</javaProperty>
			<multiple>false</multiple>
		</column>
	</sheet>
	<sheet sheetName="CSAxis(CA#)" idColumn="A" idPrefix="CA" headerRow="2" firstDataRow="4" firstDataColumn="B">
		<importType>org.iso.registry.api.registry.registers.gcp.cs.CoordinateSystemAxisItemProposalDTO</importType>
		<exportType>org.iso.registry.core.model.cs.CoordinateSystemAxisItem</exportType>
		<itemClassName>CoordinateSystemAxis</itemClassName>
		<column columnName="B">
			<javaProperty>name</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="C">
			<javaProperty>aliases</javaProperty>
			<multiple>true</multiple>
		</column>
		<column columnName="D">
			<javaProperty>remarks</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="E">
			<javaProperty>axisAbbreviation</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="F">
			<javaProperty>axisDirection.code</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="G">
			<javaProperty>axisUnit</javaProperty>
			<multiple>false</multiple>
			<references>UoM(UM#)</references>
		</column>
		<column columnName="H">
			<javaProperty>minimumValue</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="I">
			<javaProperty>maximumValue</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="J">
			<javaProperty>rangeMeaning</javaProperty>
		</column>
		<column columnName="K">
			<javaProperty>informationSource</javaProperty>
			<multiple>true</multiple>
			<references>Source_Citation(CI#)</references>
		</column>
		<column columnName="L">
			<javaProperty>justification</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="M">
			<javaProperty>registerManagerNotes</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="N">
			<javaProperty>controlBodyNotes</javaProperty>
			<multiple>false</multiple>
		</column>
	</sheet>
	<sheet sheetName="CoordSys(CS#)" idColumn="A" idPrefix="CS" headerRow="2" firstDataRow="4" firstDataColumn="B">
		<importType>org.iso.registry.api.registry.registers.gcp.cs.CoordinateSystemItemProposalDTO</importType>
		<exportType>org.iso.registry.core.model.cs.CoordinateSystemItem</exportType>
		<itemClassName>VerticalCS</itemClassName>
		<itemClassName>SphericalCS</itemClassName>
		<itemClassName>EllipsoidalCS</itemClassName>
		<itemClassName>CartesianCS</itemClassName>
		<column columnName="B">
			<javaProperty>name</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="C">
			<javaProperty>aliases</javaProperty>
			<multiple>true</multiple>
		</column>
		<column columnName="D">
			<javaProperty>#itemClassName</javaProperty>
			<multiple>false</multiple>
			<valueMapper>org.iso.registry.api.registry.registers.gcp.ItemClassNameMapper</valueMapper>
		</column>
		<column columnName="E">
			<javaProperty>remarks</javaProperty>
			<multiple>false</multiple>
		</column>
		<column columnName="F">
